name: C Embedded CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Library
      run: |
        gcc -c src/dextro_iot.c -I include -o dextro_iot.o
        ar rcs libdextro_iot.a dextro_iot.o
